apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: core
spec:
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: aditirvan/istio-sample-app:products
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
